import 'dart:math';

class WordProblem  {
  final Random random = Random();
  final List<String> mathQuestions = [
    "John has \${Number1} pencils, and Sarah gives him \${Number2} more. How many pencils does John have now?",
    "A tree has \${Number1} birds. \${Number2} more birds fly in. How many birds are on the tree?",
    "Sam buys \${Number1} apples and \${Number2} bananas. How many fruits does he have?",
    "There are \${Number1} kids playing. \${Number2} more join them. How many kids are there now?",
    "Lisa bakes \${Number1} cookies in the morning and \${Number2} in the afternoon. How many cookies does she bake in total?",
    "A classroom has \${Number1} desks and \${Number2} chairs. How many pieces of furniture are there?",
    "Emma scores \${Number1} points in one test and \${Number2} in another. What is her total score?",
    "The library has \${Number1} fiction books and \${Number2} non-fiction books. How many books are there in total?",
    "Peter solves \${Number1} math problems in class and \${Number2} at home. How many problems does he solve altogether?",
    "There are \${Number1} students in Grade 3 and \${Number2} in Grade 4. How many students are in both grades?",
    "Mike buys \${Number1} chocolate bars and \${Number2} bags of chips. How many items does he buy?",
    "A toy store sells \${Number1} cars in the morning and \${Number2} in the evening. How many cars are sold?",
    "Mary spends \$\${Number1} on shoes and \$\${Number2} on a bag. How much does she spend in total?",
    "A bakery sells \${Number1} loaves of bread and \${Number2} cakes. How many items do they sell?",
    "Mia buys \${Number1} dolls and \${Number2} teddy bears. How many toys does she buy?",
    "Tom has \${Number1} cousins, and his brother has \${Number2} cousins. How many cousins do they have together?",
    "A family has \${Number1} cats and \${Number2} dogs. How many pets do they have in total?",
    "Anna visits \${Number1} friends on Monday and \${Number2} on Tuesday. How many friends does she visit?",
    "Grandma makes \${Number1} sandwiches, and Mom makes \${Number2}. How many sandwiches are made?",
    "Ben invites \${Number1} friends to his birthday and \${Number2} to his picnic. How many friends does he invite?",
    "A park has \${Number1} benches and \${Number2} swings. How many pieces of equipment are there?",
    "A pond has \${Number1} ducks and \${Number2} frogs. How many animals are there in total?",
    "Two trees have \${Number1} and \${Number2} apples. How many apples are there in total?",
    "A car travels \${Number1} miles in the morning and \${Number2} in the evening. How far does it travel?",
    "A bus has \${Number1} seats upstairs and \${Number2} downstairs. How many seats are there in total?",
    "A plane carries \${Number1} passengers on one trip and \${Number2} on another. How many passengers in total?",
    "A team scores \${Number1} goals in the first half and \${Number2} in the second. How many goals do they score?",
    "Lily runs \${Number1} km in the morning and \${Number2} in the evening. How far does she run?",
    "A basketball player scores \${Number1} points in one game and \${Number2} in another. What is his total score?",
    "A swimmer completes \${Number1} laps in the morning and \${Number2} in the afternoon. How many laps in total?",
    "A bookshelf has \${Number1} novels and \${Number2} encyclopedias. How many books are there?",
    "A chef prepares \${Number1} meals in the morning and \${Number2} in the evening. How many meals are prepared?",
    "A gym has \${Number1} treadmills and \${Number2} weight machines. How many machines are there?",
    "An employee completes \${Number1} tasks in the morning and \${Number2} in the afternoon. How many tasks are completed?",
    "A store sells \${Number1} apples and \${Number2} oranges. How many fruits are sold in total?",
    "A plane flies \${Number1} miles in the morning and \${Number2} in the evening. How far does it fly?",
    "A Christmas tree is decorated with \${Number1} ornaments and \${Number2} lights. How many decorations are there?",
    "A company ships \${Number1} laptops in one month and \${Number2} in the next. How many are shipped?",
    "A developer writes \${Number1} lines of code in one day and \${Number2} the next. How many lines in total?",
    "A gamer plays \${Number1} levels in the morning and \${Number2} in the evening. How many levels are played?",
    "A florist arranges \${Number1} roses and \${Number2} tulips. How many flowers are there?",
    "A baker prepares \${Number1} muffins in the morning and \${Number2} in the evening. How many muffins are baked?",
    "A football team wins \${Number1} matches in one season and \${Number2} the next. How many matches do they win in total?",
    "An artist paints \${Number1} canvases in January and \${Number2} in February. How many paintings are completed?",
    "A school has \${Number1} teachers and \${Number2} assistants. How many staff members are there?",
    "A train stops at \${Number1} stations before lunch and \${Number2} after. How many stops in total?",
    "A doctor sees \${Number1} patients in the morning and \${Number2} in the afternoon. How many patients are treated?",
    "A farmer plants \${Number1} trees this year and \${Number2} next year. How many trees in total?",
    "A child has \${Number1} marbles and wins \${Number2} more. How many marbles does the child have?",
    "A carpenter builds \${Number1} chairs and \${Number2} tables. How many furniture pieces are made?",
    "A musician plays \${Number1} songs in a concert and \${Number2} during rehearsal. How many songs in total?",
    "A chef cuts \${Number1} vegetables for lunch and \${Number2} for dinner. How many vegetables are chopped?",
    "A student reads \${Number1} pages in the morning and \${Number2} at night. How many pages are read?",
    "A train has \${Number1} compartments and \${Number2} seats per compartment. How many seats in total?",
    "A soccer player kicks \${Number1} goals in one season and \${Number2} the next. How many goals in total?",
    "A company produces \${Number1} phones in January and \${Number2} in February. How many phones are made?",
    "A factory makes \${Number1} toys in the first shift and \${Number2} in the second. How many toys are made?",
    "A driver travels \${Number1} km in the morning and \${Number2} in the afternoon. How far does he travel?",
    "A store sells \${Number1} pairs of shoes on Monday and \${Number2} on Tuesday. How many pairs are sold?",
    "A zoo has \${Number1} lions and \${Number2} tigers. How many big cats are in the zoo?",
    "A family eats \${Number1} slices of pizza for lunch and \${Number2} for dinner. How many slices in total?",
    "A magician performs \${Number1} tricks in one show and \${Number2} in another. How many tricks are performed?",
    "A factory produces \${Number1} cars in the first quarter and \${Number2} in the second. How many cars are made?",
    "A class has \${Number1} boys and \${Number2} girls. How many students are in the class?",
    "A fisherman catches \${Number1} fish in the morning and \${Number2} in the evening. How many fish in total?",
    "A delivery truck carries \${Number1} packages in one trip and \${Number2} in another. How many packages are delivered?",
    "A boy collects \${Number1} stamps in January and \${Number2} in February. How many stamps does he have?",
    "A garden has \${Number1} rose bushes and \${Number2} sunflowers. How many plants in total?",
    "A scientist performs \${Number1} experiments in the lab and \${Number2} in the field. How many experiments in total?",
    "A musician practices \${Number1} hours in the morning and \${Number2} in the evening. How many hours in total?",
    "A store sells \${Number1} apples on Friday and \${Number2} on Saturday. How many apples are sold?",
    "A spaceship carries \${Number1} astronauts in the first mission and \${Number2} in the second. How many astronauts in total?",
    "A baker decorates \${Number1} cakes for a party and \${Number2} for a wedding. How many cakes in total?",
    "A team completes \${Number1} tasks before lunch and \${Number2} after. How many tasks are completed?",
    "A school orders \${Number1} textbooks and \${Number2} workbooks. How many books are there?",
    "A singer records \${Number1} songs for one album and \${Number2} for another. How many songs are recorded?",
    "A movie theater sells \${Number1} tickets in the morning and \${Number2} at night. How many tickets are sold?",
    "A runner completes \${Number1} laps on Monday and \${Number2} on Tuesday. How many laps in total?",
    "A shopkeeper sells \${Number1} chocolates and \${Number2} candies. How many sweets in total?",
    "A warehouse stores \${Number1} boxes of electronics and \${Number2} of clothes. How many boxes are there?",
    "A company hires \${Number1} new employees in the first half of the year and \${Number2} in the second. How many new employees?",
    "A factory produces \${Number1} bicycles in summer and \${Number2} in winter. How many bicycles are made?",
    "A farmer milks \${Number1} cows in the morning and \${Number2} in the evening. How many cows are milked?",
    "A boy runs \${Number1} meters in a race and \${Number2} in training. How many meters in total?",
    "A company donates \${Number1} computers to one school and \${Number2} to another. How many computers in total?",
    "A tourist visits \${Number1} cities in one country and \${Number2} in another. How many cities in total?",
    "A bakery sells \${Number1} croissants and \${Number2} doughnuts. How many pastries are sold?",
    "A soldier carries \${Number1} bullets in his rifle and \${Number2} in reserve. How many bullets does he have?",
    "A professor writes \${Number1} research papers in one year and \${Number2} the next. How many papers in total?",
    "A rescue team saves \${Number1} people in one disaster and \${Number2} in another. How many lives are saved?",
    "A tailor stitches \${Number1} shirts in one week and \${Number2} in another. How many shirts are made?",
    "A company assembles \${Number1} laptops and \${Number2} tablets. How many devices in total?",
    "A fire truck carries \${Number1} liters of water and \${Number2} liters of foam. How many liters in total?",
    "A journalist writes \${Number1} articles in a month and \${Number2} in another. How many articles in total?",
    "A team builds \${Number1} houses in one year and \${Number2} the next. How many houses are built?",
    "A family eats \${Number1} pancakes for breakfast and \${Number2} for lunch. How many pancakes in total?",
    "A bridge is supported by \${Number1} pillars on one side and \${Number2} on the other. How many pillars in total?",
    "A photographer clicks \${Number1} photos in the morning and \${Number2} in the evening. How many photos in total?",
    "A bookshop stocks \${Number1} novels and \${Number2} magazines. How many reading materials in total?",
    "A school cafeteria serves \${Number1} meals for lunch and \${Number2} for dinner. How many meals are served in total?",
    "A firefighter rescues \${Number1} cats and \${Number2} dogs. How many animals are rescued?",
    "A gardener plants \${Number1} flowers in spring and \${Number2} in summer. How many flowers are planted?",
    "A student writes \${Number1} words in an essay and \${Number2} in a report. How many words are written?",
    "A bakery sells \${Number1} cupcakes in the morning and \${Number2} in the evening. How many cupcakes are sold?",
    "A teacher grades \${Number1} papers in the morning and \${Number2} in the afternoon. How many papers are graded?",
    "A zoo has \${Number1} giraffes and \${Number2} zebras. How many animals are there?",
    "A painter uses \${Number1} liters of red paint and \${Number2} liters of blue paint. How much paint is used in total?",
    "A pet store sells \${Number1} puppies and \${Number2} kittens. How many pets are sold?",
    "A train travels \${Number1} km before noon and \${Number2} km after noon. How many kilometers does it travel in total?",
    "A postman delivers \${Number1} letters in the morning and \${Number2} in the afternoon. How many letters are delivered?",
    "A fisherman catches \${Number1} fish in the river and \${Number2} in the sea. How many fish are caught?",
    "A pizza shop makes \${Number1} small pizzas and \${Number2} large pizzas. How many pizzas are made?",
    "A cycling team covers \${Number1} km on day one and \${Number2} km on day two. How far do they ride?",
    "A science lab has \${Number1} test tubes and \${Number2} beakers. How many items are there in total?",
    "A soccer team plays \${Number1} matches in one tournament and \${Number2} in another. How many matches in total?",
    "A video game store sells \${Number1} action games and \${Number2} puzzle games. How many games are sold?",
    "A delivery driver transports \${Number1} packages in the morning and \${Number2} in the afternoon. How many packages in total?",
    "A company installs \${Number1} solar panels on one building and \${Number2} on another. How many panels are installed?",
    "A farmer grows \${Number1} watermelons and \${Number2} melons. How many fruits in total?",
    "A bakery bakes \${Number1} loaves of bread in the first batch and \${Number2} in the second. How many loaves in total?",
    "A theme park has \${Number1} roller coasters and \${Number2} water rides. How many rides are there?",
    "A company prints \${Number1} newspapers in the morning and \${Number2} in the evening. How many newspapers in total?",
    "A train station has \${Number1} arriving trains and \${Number2} departing trains. How many trains in total?",
    "A jewelry store sells \${Number1} gold necklaces and \${Number2} silver necklaces. How many necklaces are sold?",
    "A library orders \${Number1} new books in January and \${Number2} in February. How many books in total?",
    "A teacher hands out \${Number1} math worksheets and \${Number2} science worksheets. How many worksheets in total?",
    "A phone manufacturer produces \${Number1} smartphones in one month and \${Number2} in the next. How many phones in total?",
    "A baker decorates \${Number1} birthday cakes and \${Number2} wedding cakes. How many cakes are decorated?",
    "A basketball player attempts \${Number1} free throws and \${Number2} three-pointers. How many shots in total?",
    "A construction company builds \${Number1} houses in the city and \${Number2} in the suburbs. How many houses in total?",
    "A fast-food restaurant serves \${Number1} burgers and \${Number2} sandwiches. How many meals are served?",
    "A tailor sews \${Number1} shirts and \${Number2} trousers. How many clothing items are made?",
    "A fashion store sells \${Number1} dresses in summer and \${Number2} in winter. How many dresses in total?",
    "A hairdresser cuts \${Number1} men's hair and \${Number2} women's hair. How many haircuts are done?",
    "A furniture store sells \${Number1} sofas and \${Number2} beds. How many furniture pieces are sold?",
    "A carpenter builds \${Number1} tables in the workshop and \${Number2} at a customer’s house. How many tables in total?",
    "A bakery prepares \${Number1} cupcakes for a wedding and \${Number2} for a birthday party. How many cupcakes in total?",
    "A theater screens \${Number1} action movies and \${Number2} comedy movies. How many movies are shown?",
    "A bookstore sells \${Number1} fiction books and \${Number2} non-fiction books. How many books are sold?",
    "A hospital has \${Number1} doctors and \${Number2} nurses. How many medical professionals are there?",
    "A pilot flies \${Number1} domestic flights and \${Number2} international flights. How many flights does the pilot complete?",
    "A music store sells \${Number1} guitars and \${Number2} pianos. How many instruments are sold?",
    "A fitness trainer assists \${Number1} clients in the morning and \${Number2} in the evening. How many clients are trained?",
    "A chef cooks \${Number1} meals for lunch and \${Number2} for dinner. How many meals in total?",
    "A grocery store stocks \${Number1} milk cartons and \${Number2} juice bottles. How many drinks are available?",
    "A race car driver completes \${Number1} laps in one race and \${Number2} in another. How many laps in total?",
    "A tech company releases \${Number1} apps in one year and \${Number2} in the next. How many apps in total?",
    "A post office receives \${Number1} letters and \${Number2} parcels. How many items are received?",
    "A warehouse stores \${Number1} televisions and \${Number2} washing machines. How many appliances in total?",
    "A dairy farm produces \${Number1} liters of milk in the morning and \${Number2} in the evening. How many liters in total?",
    "A university enrolls \${Number1} new students in spring and \${Number2} in fall. How many students in total?",
    "A space mission launches \${Number1} satellites in one mission and \${Number2} in another. How many satellites in total?",
    "A mountain climber ascends \${Number1} meters in one trip and \${Number2} in another. How many meters in total?",
    "A scientist writes \${Number1} research papers in one year and \${Number2} in the next. How many papers in total?",
    "A hotel accommodates \${Number1} guests in January and \${Number2} in February. How many guests in total?",
    "A travel agency books \${Number1} flights in summer and \${Number2} in winter. How many flights are booked?",
    "A fisherman catches \${Number1} crabs in the morning and \${Number2} in the evening. How many crabs are caught?",
    "A fruit vendor sells \${Number1} pineapples and \${Number2} mangoes. How many fruits are sold?"


  ];
  int sum =0 ;
  int getRandomNumber() {
    int num = random.nextInt(100) + 1;
    sum += num;
    return num;
  }

  List<dynamic> getQuestion() {
    String questionTemplate = mathQuestions[random.nextInt(mathQuestions.length)];

    int num1 = getRandomNumber();
    int num2 = getRandomNumber();
    int sum = num1 + num2;
    String question = questionTemplate.replaceAll("\${Number1}", num1.toString()).replaceAll("\${Number2}", num2.toString());
    return [question, null, null, null, sum];
  }

}
